* B-friable
Also known as n-smooth, where n can be pretty much any letter.
** Applications in Computational Number Theory
 
*** Citation
@inproceedings{Granville2008SmoothNC,
  title={Smooth numbers: computational number theory and beyond},
  author={Andrew Granville},
  year={2008}
  }
*** Link
https://dms.umontreal.ca/~andrew/PDF/msrire.pdf

*** Factorization Algorithms and Cryptography
Given sufficiently large numbers, there is currently no known efficient non-quantum prime factorization algorithm.
The difficulty of the prime factorization problem is leveraged by cryptographers to build cryptographic systems (RSA) that are difficult to crack using even the current most efficient algorithm, the General Number Field Sieve, on hundreds of specialized computers (one can imagine the near impossibility of randomly guessing the factorization). Given the rise of cyber crime, espionage, and the world's reliance on computers, it has become more important than ever to ensure that effective cryptographic systems exist. To this end, factorization algorithms are constantly evolving in order to attack and prove the effectiveness of algorithms that rely on the difficulty of the prime factorization problem (some of these algorithms can be applied on discrete logarithm problem based cryptography).

Excercise:

Factor the following integer into primes:
RSA-130 = 1807082088687404805951656164405905566278102516769401349170127021450056662540244048387341127590812303371781887966563182013214880557

Hint: RSA-130 has only two prime factors.

Solution: 
RSA-130 = 39685999459597454290161126162883786067576449112810064832555157243
        \times 45534498646735972188403686897274408864356301263205069600999044599

The history of factorization algorithms is rich and deep; For the sake of brevity, we quickly describe a condensed history of factorization algorithms leading to the General Number Sieve, briefly describe how smooth numbers play a central role in their discovery, and suggest materials for in depth details.

**** Dixon's Random Squares Factoring (1981)
We begin by stating the congruence of squares problem: Determine random integers $a,b$ such that $a^2\congb^2 (\mod n)
(How does Fermat's actually solve it?)
Fermat's Factorization Method works by selecting random values for $x$ until $x^2 (\mod n)$ is a perfect square, which can be computationally expensive. Dixon's algorithm utilizes B-smooth numbers to relax Fermat's method to provide a cheaper computation. Additionally, with a result from Pomerance's Multiplicative Independence for Random Integers, Dixon rigorously proves the expected runtime of his algorithm, that is, it does not rely on conjectures.

**** Quadratic Number Sieve
The Quadratic Sieve discovered by Pomerance held the record for the largest factored number in 1983 (71 digits, which took 9.5 hours) and is designed around B-smooth numbers, taking a smoothness bound B and and the number of B-smooth primes as some of its inputs.

https://math.dartmouth.edu/~carlp/PDF/paper52.pdf
https://math.dartmouth.edu/~carlp/PDF/qs08.pdf

**** General Number Sieve
Pomerance describes in (CITE) that in 1994, his quadratic number sieve had factored RSA-129, however, Pollard's General Number Sieve (GNS) successfully factored RSA-130 in 15\% of the time that the quadratic number sieve would have taken. At the risk of oversimplification, GNS requires the selection of two polynomials, $F,G$ with which we search for coprime pairs such that the integer F(a,b)G(a,b) is $B$-smooth. Thus probability of finding such pairs (which depends on the choice of polynomials) is inversely proportional to the runtime of the algorithm, that is, the higher the probability the faster the algorithm runs.


https://www.ams.org/notices/199612/pomerance.pdf

*** Other Number Theoretic Results
https://eprint.iacr.org/2008/437.pdf

Also illustrates how properties of smooth numbers can be used to crack weak cryptographic systems and creating strong hashing (Very Smooth Hash) functions, primality tests, and error correcting functions.


* Applications in Computation
*** Fast Fourier Transform

*** Hamming Numbers
The set of numbers that are 5-smooth are called regular numbers, and characterized by having only powers of 2,3, and 5 in their factorization. In Babylonian mathematics (their number system was in base 60), regular numbers have finite reciprocals, which they kept tables of.

https://archive.org/details/disciplineofprog0000dijk/page/129/mode/2up


* Other 
https://math.dartmouth.edu/~carlp/20130813152344967.pdf
https://maths-people.anu.edu.au/~brent/pd/Bai-thesis.pdf
